spring:
  datasource:
    url: jdbc:h2:file:./devschool;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: admin
    password: password
    driver-class-name: org.h2.Driver
  jpa.show-sql: true
  jpa.hibernate.ddl-auto: update